server:
  port: 3001
spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
---
#本地运行环境
spring:
  profiles: local
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/cplay?serverTimezone=GMT%2B8
      username: root
      password: 123456
      initial-size: 10
      max-active: 300
      min-idle: 0
      max-wait: 1000